# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Id аккаунта телеграм')),
                ('state', models.CharField(default='', max_length=150, verbose_name='Состояние')),
                ('is_student', models.BooleanField(default=False, verbose_name='Учащийся')),
                ('group_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер группы')),
                ('data', models.CharField(blank=True, max_length=200, null=True, verbose_name='Информация для state')),
            ],
        ),
    ]
