# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
    ]
