# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teachers_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость имен преподавателей'),
        ),
    ]
