# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0002_user_teachers_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id аккаунта телеграм'),
        ),
    ]
