# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0002_auto_20170201_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_state',
            new_name='state',
        ),
    ]
