# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0003_auto_20170202_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уведомления'),
        ),
    ]
