# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0004_user_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_time',
            field=models.IntegerField(blank=True, choices=[(1, '7:00'), (2, '7:30'), (3, '8:00')], null=True, verbose_name='Уведомления'),
        ),
    ]
