# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0005_auto_20170205_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Время уведомления'),
        ),
    ]
